//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceBlender.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public int Id { get; set; }
        public int Language_Id { get; set; }
        public int Resource_Id { get; set; }
        public string TranslationString { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
